java/Makefile
The `test` target in the Java Makefile has an incorrect dependency graph
that could cause tests to start executing before the compilation finished
(or even started) when make is invoked in job server mode.
Fix it by specifying target dependencies such that running the tests depends
on having the tests compiled first.
=> build: fix the java test target dependencies (#128)

db/flush_job.cc
Rolling back in these cases is meaningless because the memtables will be
freed shortly afterwards, so making them available for flush again is useless
at best.
Additionally, in atomic flush, memtables that were successfully flushed
aren't rolled back if a CF is dropped or a DB shutdown was requested (the
shutdown case is the more relevant one for the comparison here because it
aborts the flush, whereas the in the CF drop case it's simply ignored at
flush result installation time). In this regard this change simply matches
the behaviour there.
Lastly, this might be needed for the WriteBufferManager changes in #113,
since we plan to use the information about memory that can be flushed in
the future for triggering flushes based on immutable memory as well, and
rolling back flushes causes the …
=> flush_job: do not roll back memtable flush on CF drop and DB shutdown (#126)

util/bloom_test.cc
When compiling bloom_test with GCC 12 it complains about using uninitialised
variables. The error is technically wrong, since only the address is taken,
but since this is a test and there's no performance penalty, initialise
the member to get rid of the error.
=> bloom_test: fix compilation error with GCC 12 (#136)

CMakeLists.txt, Makefile
Add a xxx_TESTS variable that contains the tests to build for the plugin.  Create rules in CMake and Make to build the corresponding tests.
Note that the same paradigm can be used to build most/all tests, but was left for a second PR (to not complicate the change)
=> Add Plugin Tests to builds

.gitignore, Makefile, common.mk
The changes in #119 included an upstream commit that moved the TEST_TMPDIR
setting to common.mk and executed it unconditionally.
This is causing pollution of /dev/shm unnecessarily, and also causes the
crash tests and other targets to use /dev/shm when they originally didn't.
On machines with small /dev/shm this leads to the crash tests failing with
an out of space error.
Make the setting of TEST_TMPDIR and the creation of a temporary directory
under it execute only once during a single make invocation and only for
the check target, as it was originally. This requires dealing with make
restarts (due to makefiles getting remade) in the form of adding another
temporary configuration file named test_config.mk
=> makefile: avoid setting TEST_TMPDIR unnecessarily (#140)

Makefile, java/Makefile
egrep and fgrep have been deprecated for a long time in GNU grep, and as of release 3.8 using them prints a warning message, as stated in the 3.8 release notes:
> The egrep and fgrep commands, which have been deprecated since
> release 2.5.3 (2007), now warn that they are obsolescent and should
> be replaced by grep -E and grep -F.
egrep is used during the build to query the version, and with the warning that's now being printed this adds unneeded noise to the output of the build. Replace the usage of egrep with grep -E to get rid of the warning.
=> build: replace usages of egrep with grep -E (#166)

tools/db_crashtest.py
The debugging backup logic in whitebox wasn't cleaning up DB copies on
timeout because the cleanup logic was inside the loop. Move it to the end
of the function to ensure that backups are cleaned up on success.
Also make sure to clean up DB backup copies in the narrow test.
=> crash_test: clean up DB copies in whitebox and narrow test (#159)

tools/db_bench_tool.cc
This would allow us to compare the performance of changes related to background purges using db_bench.
=> db_bench: allow setting avoid_unnecessary_blocking_io (#183)

CMakeLists.txt, Makefile, cmake/CTestRunner.cmake
Allow running tests in parallel by default by setting the CTEST_PARALLEL_LEVEL
environment variable. The functionality is added using a CMake script in
order to determine options when running the tests (rather than when configuring
CMake) in compatibility with the Makefile (in particular -- the `J` and
`TEST_TMPDIR` environment variables).
Test Plan: run the check target using different generators (ninja, make)
to see the improvement in test runtime.
=> cmake: allow running the tests in parallel like in the Makefile (#102)

db/column_family_test.cc, db/db_compaction_test.cc, db/db_flush_test.cc, db/db_impl/db_impl_compaction_flush.cc, db/db_options_test.cc, db/db_test.cc, db/db_wal_test.cc, db/deletefile_test.cc, include/rocksdb/options.h
This is done through the deprecated `max_background_compactions` option, which overrides `max_background_jobs`, so in order to avoid having an adverse effect on users who set `max_background_jobs` to a high value we try to detect that case and shift back to the user's choice in case there are enough background jobs to be enough for both flushes and compactions.
Test plan: run `make check` with the fixed unit tests.
=> options: change the default value for compaction threads to 8 (#169)

db/db_compaction_test.cc, db/db_range_del_test.cc, db/deletefile_test.cc
In #194 the default value for background compaction threads was changed to 8 (from 1). This caused some tests to fail, but they were fixed. Alas, the fixes seems to not be complete, as under stress some tests still fail.
Make it so the tests are truly fixed now. This can be checked by running them in a loop with the machine overloaded:
```
$ while ./db_compaction_test --gtest_filter=DBCompactionTestWithParam/DBCompactionTestWithParam.PartialCompactionFailure/1; do sleep 1; done
```
And
```
$ while ./deletefile_test --gtest_filter=DeleteFileTest.BackgroundPurgeCopyOptions; do sleep 1; done
```
=> tests: fix breakage caused by the compaction threads value change (#197)

plugin/speedb/paired_filter/speedb_db_bloom_filter_test.cc, plugin/speedb/paired_filter/speedb_paired_bloom.cc, plugin/speedb/paired_filter/speedb_paired_bloom.h, plugin/speedb/paired_filter/speedb_paired_bloom_internal.cc, plugin/speedb/paired_filter/speedb_paired_bloom_internal.h, plugin/speedb/speedb_customizable_test.cc
The paired Bloom filter files are either missing a copyright notice and licence header, or contain the wrong one. Fix that in order to adhere to the contribution guidelines.
=> paired_filter: fix copyright and licence headers (#199)

CMakeLists.txt, Makefile, build_tools/spdb_get_build_tag.py, util/build_version.cc.in
The build tag can be set during the build (using either the Makefile or the CMake). If it's not provided, and we're not in a release build, it will be calculated using the state of the git tree since the last release tag (for example, for this PR the build tag will be calculated as `(main+17)-(156-build-add-a-build-tag-into-the-version-for-non-release-builds+1)`.
If the git tree state can not be determined, a question mark will be used instead.
=> build: add a version build-tag for non-release builds (#156)

Makefile, build_tools/build_detect_platform
Add support for detecting and using ccache/sccache to the Makefile build in order to speed up build times as it's done in the CMake configuration.
=> build: support ccache and sccache in the Makefile build (#170)

db/column_family_test.cc, db/memtable_list.cc
This is a continuation of #126 with changes that were missed there in case
a CF drop was encountered after the flush was completed but before or during
manifest write.
Rolling back on CF drop is meaningless because a flush is not possible
in that state, and the only path forwards is for the memtables to be freed
shortly afterwards, so making them available for flush again is useless
at best.
Additionally, this might be needed for the WriteBufferManager changes in
in the future for triggering flushes based on immutable memory as well,
and rolling back flushes causes the memtable memory to become ready for
flush again for a brief period of time until it is dropped, which might
wrongly affect the WBM decisions.
Finally, the code installs a new version even if no changes are made. This
is …
=> memtable_list: avoid rolling back memtable flush on CF drop (#144)

db/deletefile_test.cc
In #194 the default value for background compaction threads was changed to 8 (from 1). This caused some tests to fail and fixes were implemented as part of #197. Alas, it seems that the fixes weren't complete, as under stress a test still fail.
Make it so the test is truly fixed now. This can be verified by running them in a loop with the machine overloaded:
```
$ while ./deletefile_test --gtest_filter=DeleteFileTest.BackgroundPurgeCFDropTest; do sleep 1; done
```
=> deletefile_test: fix breakage caused by the compaction threads change

INSTALL.md, README.md
Both were incorrectly referencing the old artefact names before the changes in #66.
=> docs: fix instructions for building Speedb in README.md and INSTALL.md

util/build_version.cc.in
The changes in #157 were accidentally applied to the `GetRocksVersionAsString()` function instead of the `GetSpeedbVersionAsString()` function. This replaced the RocksDB patch number with the Speedb one, and added the build tag in the wrong place.
Fix it by moving the logic to the intended function.
=> build_version: apply the build tag to the Speedb version string (#231)

.github/workflows/artifact-release.yml
Specify `SPDB_RELEASE_BUILD` to both CMake and the Makefile builds in order to get the release artefacts to build without a build tag of `?`.
=> ci: build a release without a debug tag (#228)

build_tools/spdb_get_build_tag.py
Merge commits were incorrectly handled due to the named use of `git rev-list`, which does not give an ancestry path as I expected, but simply a list of unique commits between the two refs.
Additionally, the check for the base tag was wrong in the face of merge commits, since a tag could be an ancestor through a merge commit, but not be the actual base of the branch.
Both of these issues resulted in an incorrect tag being calculated, as well as a build slowdown due to the iteration over all of the commits from the other parent of the merge commit, which is unneeded. After the changes in this PR, running the script on the branch mentioned in the linked issue (#225) results in the following output:
```
$ build_tools/spdb_get_build_tag.py
warning: current version doesn't match base release …
```
=> build: correctly handle merge commits when calculating a build tag

include/rocksdb/memtablerep.h, options/customizable_test.cc, plugin/speedb/memtable/hash_spd_rep.cc, plugin/speedb/memtable/hash_spd_rep.h
generic switch memtable allows the ability to pre create memtable that allocated memory as part of the constructor
this will reduce the penelty time of switch mutable memtable which by definition will effect write flow
=> generic switch memtable 

db/column_family.h, db/db_impl/db_impl.cc, db/db_impl/db_impl.h, db/db_impl/db_impl_compaction_flush.cc, db/db_impl/db_impl_open.cc, db/db_impl/db_impl_write.cc, db/db_test2.cc, db/db_write_buffer_manager_test.cc, db/flush_job.cc, db_stress_tool/db_stress_common.h, db_stress_tool/db_stress_gflags.cc, db_stress_tool/db_stress_test_base.cc, db_stress_tool/db_stress_tool.cc, include/rocksdb/listener.h, include/rocksdb/write_buffer_manager.h, memtable/write_buffer_manager.cc, memtable/write_buffer_manager_test.cc, tools/db_bench_tool.cc, tools/db_crashtest.py
@isaac-io - This is a preliminary version not yet ready.
However, due to the time pressure, I would really appreciate your review.
Please focus on the production code parts and leave the unit testing part for later.
Thanks
=> 155 proactive wbm flushes

db/compaction/compaction_service_test.cc
the test assumes that each compaction job_id from the remote compaction is unique but in fact all the job_ids are 1.
the test passed thus far since there was just 1 bg compaction by default. once we increased it to 8, there could be concurrent remote compactions which led to this error.
=> unit tests: fix CompactionServiceTest.RemoteEventListener (#314)

Makefile, build_tools/gtest_parallel.py
Instead, use gtest-parallel as a bundled script for running both gtest tests and non-gtest tests (such as c_test, for example).
=> build: remove the dependency on GNU Parallel for running unit tests

tools/db_bench_tool.cc
actual values that have changed:
1. index_shortening_mode - from 2 (kShortenSeparatorsAndSuccessor) to 1 (kShortenSeparators)
2. hard_pending_compaction_bytes_limit - from 128 Gb to 256 Gb
3. delayed_write_rate - from 8Mb to 0 (0 is sanitized to 16Mb)
4. enable_pipelined_write - from true to false
=> db_bench: set db_bench defaults to speedbs (#61)

db/memtable.cc, include/rocksdb/memtablerep.h, options/cf_options.h, plugin/speedb/memtable/hash_spd_rep.cc, plugin/speedb/memtable/hash_spd_rep.h, plugin/speedb/memtable/spdb_sorted_vector.h, table/internal_iterator.h, tools/db_bench_tool.cc
review already done by @hilikspdb for that version
=> Improve spdb memtable performance (#298)

tools/db_bench_tool.cc
fix seekrandomwriterandom, BGWriter, readrandom, seekrandom and readrandomwriterandom.
made sure these tests:
1. use one rand num to get the db and cf and the key which makes it possible to find a key in a cf later on.
2. ability to have a read and write limiter where ever relevant.
3. operations are done on all cfs randomly and not only on the default cf
=> 325 db bench align the tests we're using

db/db_test_util.cc, test_util/testharness.cc, test_util/testharness.h
This PR is based on the following [RocksDB PR](https://github.com/facebook/rocksdb/pull/10000).
The name of the database directory can be based on the name of the test itself.  This allows multiple tests in the same test class to use different database directories rather than all going to the same or similar directories.
This change can also help in debugging and KEEP_DB tests, as the directory after the test run can be spotted by its name (which is based on the name of the test).
=> Use the Test Name for the dbname when running unit tests

db/db_impl/db_impl.cc, db/db_impl/db_impl.h, db/db_options_test.cc, db/periodic_task_scheduler.cc, db/periodic_task_scheduler.h, db/periodic_task_scheduler_test.cc, db_stress_tool/db_stress_common.h, db_stress_tool/db_stress_gflags.cc, db_stress_tool/db_stress_test_base.cc, include/rocksdb/options.h, options/db_options.cc, options/db_options.h, options/options_helper.cc, options/options_settable_test.cc, tools/db_bench_tool.cc
Added a method and options to support reading configuration changes to options periodically while a process is running.  Every "refresh_options_sec", the periodic task scheduler runs a task to check if the "refresh_options_file" exists.  If it does, the file is loaded as an options file and the mutable options from the file are updated in the running process (via SetDBOptions and SetOptions).  Once updated, the refresh file is deleted.  If an error occurs, it will be written to the log file.
Note that the file is read as an Options file and must be a valid Options file.  This means that the file must have a DBOptions section and at least one ColumnFamilyOptions section.  Only options that are mutable can be in this file -- immutable options will cause an error and abort the processing. …
=> Add RefreshOptions method to support live config changes

tools/db_bench_tool.cc
Changed db_bench so that when using multiple databases (num_multi_db > 1) we only destroy databases that were used for the current group (databases specified in dbs_to_use).
=> db_bench: fix for issue #290

build_tools/check-sources.sh
Some files did not have license, added to the source file check that all speedb new source files will contain license
=> Enforce writing licenses inside a source file

Makefile
=> Makefile: Use speedb libs in `build_size` target

db/column_family.cc, db/write_controller.cc, db/write_controller.h
i encountered a bug while running tests for the dirty memory connection to the global write controller and the bug is as follows:
during WriteController::GetDelay , we check if there are enough credits and return if there are, here:
```
auto credits = credit_in_bytes_.load();
while (credits >= num_bytes) {
if (credit_in_bytes_.compare_exchange_weak(credits, credits - num_bytes))
return 0;
}
```
if there arent enough credits, we proceed under the mutex but dont check again the condition above which might have changed from a different thread. 
this PR adds this additional check and while at it, rename and reorder some members.
=> Global delay bug fix: check again credits under mutex

tools/db_crashtest.py
Theres a sanitize check in case of allow_concurrent_memtable_write == 1 which verifies that the memtablerep supports it. This commit prevents the code from rerolling if the memtablerep was originally skip_list or speedb.HashSpdRepFactory
=> crashtest: dont reroll skip_list or HashSpdRepFactory

include/rocksdb/options.h, options/db_options.cc, options/options.cc
=> options: Forward declare WriteBufferManager

db/column_family.cc
closes #431 
use fixed num delay steps instead of fixing the step size and deducing the num steps.
this makes the code simpler and avoids a bug when the excess bytes are greater than num_steps * step_size which then fails the assert: assert(step_num < num_steps);  - since step_num == num_steps.
=> dynamic delay: fix pending bytes rate calculation

build_tools/check-sources.sh, db_stress_tool/db_stress_common.h, db_stress_tool/db_stress_gflags.cc, db_stress_tool/db_stress_test_base.cc, examples/.gitignore, examples/CMakeLists.txt, examples/Makefile, examples/speedb_with_ttl_example.cc, include/rocksdb/options.h, tools/db_bench_tool.cc, utilities/ttl/db_ttl_impl.cc, utilities/ttl/db_ttl_impl.h, utilities/ttl/ttl_test.cc
Currently even if objects have been expired we still return them until
compaction delete those objects.
This commit adds a skip_expired_data to the ReadOptions, if this option
is true, it Get, MultiGet and iterator will not return objects that have been
expired by the configured ttl.
Currently this feature does not include support of for Merge
operation.
For Read Only and iterator pinned data the skip_expired_data will be enforced and expired keys
will not be returned.
Resolves: https://github.com/speedb-io/speedb/issues/394 , https://github.com/speedb-io/speedb/issues/417
=> Skip expired object while using DBWithTtl

include/rocksdb/ldb_tool.h, include/rocksdb/utilities/ldb_cmd.h, monitoring/histogram.h, monitoring/histogram_windowing.h, tools/CMakeLists.txt, tools/beezcli.cc, tools/ldb_cmd.cc, tools/ldb_cmd_impl.h, tools/ldb_test.py, tools/ldb_tool.cc
This Pull request is adding a wrapper around ldb and allow using ldb in interactive manner (it is yet possible to use it non interactive just like ldb).
It adds some new functionalities to ldb such as multiget,
summary of keys and values from dump command, allow to not present values on dump and idump.
Fix the ttl parameter, to allow ttl to get value and run compaction on top of db with ttl.
Resolves: https://github.com/speedb-io/speedb/issues/407
=> Adding beezcli

java/rocksjni/config_options.cc, java/rocksjni/filter.cc, java/rocksjni/portal.h, java/src/main/java/org/rocksdb/ConfigOptions.java, java/src/main/java/org/rocksdb/Filter.java, java/src/test/java/org/rocksdb/FilterTest.java, plugin/speedb/java/src/test/java/org/rocksdb/SpeedbFilterTest.java, plugin/speedb/speedb.mk
This PR adds the ability to create a Filter (FilterPolicy) in Java via the CreateFromString methodology.  This change allows the other filter policies (such as Ribbon Filter and plugin filters) to be created in Java using the C++ infrastructure.
=> Add Filter::CreateFromString to Java

util/xxhash.h
the previous commit disabled all the rest of the XXH optimizations since it didnt prevent the XXH_VECTOR from being defined as XXH_AVX512.
this PR fixes that.
=> AVX512: fix disabling other optimizations

db_stress_tool/no_batched_ops_stress.cc
=> Stress error utf 8 codec cant decode byte

db_stress_tool/db_stress_gflags.cc, db_stress_tool/db_stress_test_base.cc, db_stress_tool/db_stress_tool.cc, tools/db_bench_tool.cc, tools/db_crashtest.py
Please note that now the user of db_bench / db_stress must either override the default of initiate_wbm_flushes to false or leave it true, but set the db_write_buffer_size flag to a value > 0
=> Set initiate_wbm_flushes to the same default value used by the WBM (true) (#480)

HISTORY.md, db/column_family.h, db/db_impl/db_impl_write.cc, db/db_test.cc, db/db_test_util.cc, db/db_test_util.h, db/write_controller.cc, db/write_controller.h
as part of https://github.com/facebook/rocksdb/pull/10765 , a check of whether the waiting db was shutting_down_ was intoduced. 
The write thread then stops waiting when shutting_down_ is turned on which is the case when CancelAllBackgroundWork is called. But the rebased code now waits forever since #346 replaced the waiting on bg_cv_ to a wait on a write controller condition variable inside WriteController::WaitOnCV. 
The condition variable inside WaitOnCV (stop_cv_) is only notified through the detor of a StopWriteToken.
The write_controller_token_ in each CF is being reset in any case after the call to CancelAllBackgroundWork from  DBImpl::CloseHelper() (detor of DBImpl) so if the test would issue a db Close and then wait for the thread there would be no problem.
also consider fixing …
=> WC: fix for stop while shutting down

HISTORY.md, utilities/transactions/transaction_test.cc
closes #493 
When external_delay = true, a stop token is taken in addition to the LockWal stop token. when UnlockWal() is called, it releases the stop token and calls bg_cv_.SignalAll() . this wakes a sleeping writing thread to call EndWriteStall() which in turn increments stall_ended_count_. stall_ended_count_ is the counter that the UnlockWal() thread is waiting on in WaitForStallEndedCount. this is where our current code is stuck since during https://github.com/speedb-io/speedb/issues/346 , we've moved the waiting to a cv in the WriteController and not in the DB since there can be many dbs sharing a WriteController. The thread in UnlockWal() is stuck since when the writing thread wakes up (after detor of Stop Token), it does not call EndWriteStall() but simply stays in the while loop …
=> Transaction test unlock wal fix

HISTORY.md, db/global_write_controller_test.cc
RUN      ] GlobalWriteControllerTest.GlobalAndWBMSetupDelay
db/global_write_controller_test.cc:391: Failure
Value of: options.write_buffer_manager->memory_usage() < 5_kb
Actual: false
Expected: true
FAILED  ] [GlobalWriteControllerTest.GlobalAndWBMSetupDelay (44 ms)
The memory is freed only when the detor of the version is called in `job_context.Clean();` under `DBImpl::BackgroundCallFlush` .
The problem was that calling Flush with `FlushOptions.wait = true`, doesn't wait for the memory to be free which also happens during the flush process.
So the fix is adding a sync point which delays the assertion of checking the WBM memory usage to after the flush cleared the memtable memory.
=> unit tests: Fix GlobalAndWBMSetupDelay

HISTORY.md, cache/cache.cc, cache/cache_entry_roles.cc, cache/cache_entry_stats.h, cache/clock_cache.cc, cache/clock_cache.h, cache/lru_cache.cc, cache/lru_cache.h, cache/sharded_cache.h, cache/typed_cache.h, db/column_family.cc, db/column_family.h, db/db_block_cache_test.cc, db/internal_stats.cc, db/internal_stats.h, db/table_cache.cc, db/table_cache.h, include/rocksdb/advanced_cache.h, include/rocksdb/cache.h, include/rocksdb/db.h, table/block_based/block_based_table_factory.cc, table/block_based/block_based_table_reader.cc, table/block_based/block_based_table_reader.h, table/table_builder.h
The original issue is: https://github.com/speedb-io/speedb/issues/338
=> Redo of Index/Filter/Data blocks sizes in Block (LRU) Block Cache per CF after rebase on RocksDB 8.1 (#516)

HISTORY.md, build_tools/check-sources.sh, db/db_basic_test.cc, db/db_impl/db_impl_open.cc, db/db_impl/db_spdb_impl_write.h, env/env_posix.cc, examples/.gitignore, examples/CMakeLists.txt, examples/Makefile, examples/on_thread_start_callback_example.cc, include/rocksdb/db.h, include/rocksdb/env.h, include/rocksdb/memtablerep.h, include/rocksdb/options.h, include/rocksdb/port_defs.h, include/rocksdb/write_buffer_manager.h, memtable/spdb_sorted_vector.h, memtable/write_buffer_manager.cc, options/options_settable_test.cc, port/port_posix.cc, port/port_posix.h, port/win/port_win.cc, port/win/port_win.h
Add an option of callback that the db will use before spawning a thread, potentially could be used for thread affinity
fixes: https://github.com/speedb-io/speedb/issues/476
=> Add on thread start callback

HISTORY.md, tools/db_bench_tool.cc
Use key and value only after checking iterator is valid
=> db_bench: fix SeekRandomWriteRandom valid check

tools/db_bench_tool.cc
num_seek_to_first and num_next are not used in db_bench_tool. It will throw warnings and then fail to build.
```shell
/Users/hulk/code/cxx/speedb/tools/db_bench_tool.cc:7693:14: error: variable 'num_seek_to_first' set but not used [-Werror,-Wunused-but-set-variable]
uint64_t num_seek_to_first = 0;
^
/Users/hulk/code/cxx/speedb/tools/db_bench_tool.cc:7694:14: error: variable 'num_next' set but not used [-Werror,-Wunused-but-set-variable]
uint64_t num_next = 0;
```
=> Fix unused variable warnings in db_bench_tool.cc

HISTORY.md, db/column_family.cc, db/column_family.h, db/compaction/compaction_job_test.cc, db/write_controller.cc, include/rocksdb/write_buffer_manager.h, include/rocksdb/write_controller.h, memtable/write_buffer_manager.cc, tools/db_bench_tool.cc
This commit adds reporting capabilities to the WBM. Specifically, for when it sets or resets a delay request to the WriteController. This is done by adding the Logger to the WBM during DB Open, in the Ctor of ColumnFamilySet together with the WC.
=> Logger: Add reporting capabilities to the WBM

HISTORY.md, table/format.cc
Before applying this PR, the footer details:
```
Footer Details:
--------------------------------------
metaindex handle: B0E499405C
index handle: 8AC49940CD17
table_magic_number: 9863518390377041911
format version: 5
```
and after
```
Footer Details:
--------------------------------------
metaindex handle: B0E499405C offset: 134640176 size: 92
index handle: 8AC49940CD17 offset: 134636042 size: 3021
table_magic_number: 9863518390377041911
format version: 5
```
This closes #404
=> Add the offset and size to the dump SST footer details

.github/workflows/check_license_and_history.yml
check history step is unable to check the base sha due to fetch-depth not being set to 0.
``` fatal: bad object bedf640182e490efa34cd493d6a8844e394d906c ```
=> CI: Fix check history, add fetch-depth 0 for base sha

HISTORY.md, db/c.cc, db/c_test.c, include/rocksdb/c.h
Created this pr in rocksdb repo: https://github.com/facebook/rocksdb/pull/12019 but it's unclear if/when the pr will be accepted. I'm working on switching to speedb so decided to make the change directly here.
=> Expose Options::periodic_compaction_seconds via C API

HISTORY.md, include/rocksdb/options.h
The current value of 2Mb is not optimal for most of our use cases. 
By setting the value to 0, we ensure that the prefetch size during compaction read will be the default for that instance.
related to https://github.com/speedb-io/speedb/issues/787.
=> Options: Set compaction_readahead_size default to 0

HISTORY.md, db/db_options_test.cc, file/prefetch_test.cc
fix CI failure after changing compation_readahead_size default to 0
fixes: https://github.com/speedb-io/speedb/issues/793
=> fix CI failure after changing compation_readahead_size default to 0

HISTORY.md, include/rocksdb/advanced_options.h
This flag is not working properly with Speedb. see https://github.com/speedb-io/speedb/issues/786 for more details
=> Options: Set level_compaction_dynamic_level_bytes as false by default

HISTORY.md, table/block_based/block_based_table_reader.cc
In https://github.com/facebook/rocksdb/pull/11658, files are no longer controlled by the access_hint_on_compaction_start flag by removing the content of SetupForCompaction. However, this leads to degradation in compaction read speed when combined with compaction_readahead_size since once a file is opened, in linux, it is hinted with POSIX_FADV_RANDOM.
See https://github.com/speedb-io/speedb/issues/787 for full details.
Add back the default hint to avoid degradation in this scenario.
=> Compaction: Restore SetupForCompaction functionality

HISTORY.md, db/c.cc, db/c_test.c, include/rocksdb/c.h, java/CMakeLists.txt, java/Makefile, java/rocksjni/options.cc, java/src/main/java/org/rocksdb/ColumnFamilyOptions.java, java/src/main/java/org/rocksdb/ColumnFamilyOptionsInterface.java, java/src/main/java/org/rocksdb/DBOptions.java, java/src/main/java/org/rocksdb/DBOptionsInterface.java, java/src/main/java/org/rocksdb/Options.java, java/src/main/java/org/rocksdb/SharedOptions.java, java/src/test/java/org/rocksdb/SharedOptionsTest.java
fixes: https://github.com/speedb-io/speedb/issues/701
=> Add JAVA and C Interface for EnableSpeedbFeatures

HISTORY.md, tools/db_crashtest.py
TestIterateAgainstExpected was not designed to support value of 0 in FLAGS_num_iterations. RocksDB has a value of 10 by default and we've added the option to randomize the values from 0 to 100 in https://github.com/speedb-io/speedb/commit/434692a63318036a3995a53001337f18bf467903
Fix by limiting to 1 - 100.
error:
```
./db_stress --acquire_snapshot_one_in=10000 --adaptive_readahead=0 --allow_concurrent_memtable_write=1 --allow_data_in_errors=True --allow_wbm_stalls=1 --async_io=0 --avoid_flush_during_recovery=1 --avoid_unnecessary_blocking_io=1 --backup_max_size=104857600 --backup_one_in=100000 --batch_protection_bytes_per_key=0 --block_protection_bytes_per_key=2 --block_size=16384 --bloom_bits=3.242941150392554 --bottommost_compression_type=disable --bottommost_file_compaction_delay=600 …
```
=> stress test: Fix TestIterateAgainstExpected not supporting 0 iterations

HISTORY.md, include/rocksdb/listener.h
The GetFlushReasonString/GetCompactionReasonString are exported in rocksdb(PR [#11778](https://github.com/facebook/rocksdb/pull/11778))
and Apache Kvrocks would like to use them to avoid copying those reason strings: https://github.com/apache/kvrocks/pull/1962
=> Export GetFlushReasonString/GetCompactionReasonString in listener.h

HISTORY.md, db_stress_tool/expected_state.cc
This should be reverted once #813 is handled
Adding a trace file by default in #797 has revealed some incompatibilities between the trace file and several configurations (more details in #813).
Keep the trace file and remove the IsDone assertion.
=> stress test: Disable IsDone assertion which fails with tracing sometimes

HISTORY.md, db_stress_tool/db_stress_test_base.cc
There is a bug that ValidateEnableSpeedbFlags() checks for non existence parameters in db_stress
=> Remove some db stress non existence parameters

HISTORY.md, db/column_family.cc, db/write_controller.cc
The WC currently reports to the log whenever a new delay request is handled (even if its the same rate). 
These msgs are redundant in cases where the WC is only shared with 1 db and hence 1 logger since similar msgs are reported in ColumnFamilyData::RecalculateWriteStallConditions.
Currently it looks like :
```
2024/02/11-12:34:41.726676 7213 [WARN] [/write_controller.cc:153] WC setting delay of 178892456, client_id: 0x563f8a2e8f60, client rate: 178892456
2024/02/11-12:34:41.726684 7213 [WARN] [/column_family.cc:1235] [default] Stalling writes because we have 12 level-0 files rate 178892456
```
This PR removes the msg from the write_controller (the first) when there is only 1 logger to report to.
=> WriteController: Remove redundant setting delay reports with single db

CMakeLists.txt, HISTORY.md
Fix cross-compilation on macOS x86_64 CPUs with target CPU arm64 by manually setting CMAKE_SYSTEM_PROCESSOR to the cross-compilation target whenever CMAKE_SYSTEM_PROCESSOR doesn't match CMAKE_OSX_ARCHITECTURES after project() call. This is probably a Cmake bug that happens on macOS. (#822).
The issue happens when SpeeDB is built using the follwoing command:
`cmake -G "Unix Makefiles" -DCMAKE_SYSTEM_PROCESSOR=arm64 ..`
The build itself succeeds, but because Cmake wrongly sets CMAKE_SYSTEM_PROCESSOR to x86_64 instead of arm64 and causes crc32c_arm64.cc not to be compiled.
This in turn makes the project fails any linking with SpeeDB:
```
Undefined symbols for architecture arm64:
"crc32c_arm64(unsigned int, unsigned char const*, unsigned long)", referenced from: …
```
=> Fix cross-compilation on macOS x86_64 CPUs with target CPU arm64

HISTORY.md, memtable/hash_spdb_rep.cc, tools/db_bench_tool.cc
set the default bucket size of hashspdb to be 400k for best memory use and performance
=> 854: set the default bucket size of hashspdb to be 400k 
